[package]
name = "asn_tools"
version = "0.1.0"
authors = ["Jakub Pastuszek <jpastuszek@gmail.com>"]

[dependencies]
problem = "0.1.0"
csv = "1.0.2"
ipnet = "2.0.0"
cotton = { git = "https://github.com/jpastuszek/cotton.git" }
structopt = "0.2.12"
log = "0.4.6"
superslice = "0.1.0"
serde = "1.0.80"
serde_derive = "1.0.80"
bincode = "1.0.1"
itertools = "0.7.8"
app_dirs = "1.2.1"
